# Generated by Django 5.2.17 on 2026-10-01 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_productcompatibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorites', to='catalog.product')),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='favorites_customer_created_idx'), models.Index(fields=['product', 'created_at'], name='favorites_product_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='favorites_customer_product_unique')],
            },
        ),
    ]
