# Generated by Django 5.2.17 on 2026-09-24 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_store_unique_store_per_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FAILED_DELIVERY', 'Failed Delivery'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seller_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'), models.Index(fields=['store', 'status'], name='orders_orde_store_i_610c63_idx'), models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx')],
            },
        ),
    ]
