# Generated by Django 5.2.17 on 2026-09-26 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('BLOCKED', 'Blocked')], db_index=True, default='ACTIVE', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_otp', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'status'], name='orders_deli_order_i_d0239f_idx'), models.Index(fields=['status', 'expires_at'], name='orders_deli_status_669fdf_idx')],
            },
        ),
    ]
