# Generated by Django 5.2.17 on 2026-09-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliveryotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryotp',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_otps', to='orders.order'),
        ),
    ]
