# Generated by Django 5.2.17 on 2026-09-24 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('stores', '0003_store_unique_store_per_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cart.cart')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='stores.sellerproduct')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['cart', 'created_at'], name='cart_cartit_cart_id_6306fd_idx'), models.Index(fields=['seller_product'], name='cart_cartit_seller__5ad43c_idx')],
                'constraints': [models.UniqueConstraint(fields=('cart', 'seller_product'), name='unique_cart_seller_product')],
            },
        ),
    ]
