# Generated by Django 5.2.17 on 2026-09-27 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0005_deliveryassignment'),
        ('stores', '0003_store_unique_store_per_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('SETTLED', 'Settled'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='finance_com_store_i_ebcf99_idx'), models.Index(fields=['order', 'status'], name='finance_com_order_i_a777aa_idx')],
            },
        ),
    ]
