# Generated by Django 5.2.17 on 2026-09-28 02:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_commission'),
        ('stores', '0003_store_unique_store_per_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjustments_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='stores.store')),
            ],
            options={
                'db_table': 'finance_settlements',
                'indexes': [models.Index(fields=['store', 'status'], name='fin_settle_store_status_idx'), models.Index(fields=['period_start', 'period_end'], name='fin_settle_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_start__lt', models.F('period_end'))), name='fin_settle_valid_period'), models.CheckConstraint(condition=models.Q(('gross_sales__gte', 0)), name='fin_settle_gross_nonnegative'), models.CheckConstraint(condition=models.Q(('commission_total__gte', 0)), name='fin_settle_commission_nonnegative'), models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='fin_settle_net_nonnegative')],
            },
        ),
    ]
