# Generated by Django 5.2.17 on 2026-09-28 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_item', to='finance.commission')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.settlement')),
            ],
            options={
                'db_table': 'finance_settlement_items',
                'indexes': [models.Index(fields=['settlement'], name='fin_settle_item_settle_idx'), models.Index(fields=['commission'], name='fin_settle_item_comm_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='fin_settle_item_gross_nonnegative'), models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='fin_settle_item_comm_nonnegative')],
            },
        ),
    ]
