# Generated by Django 5.2.17 on 2026-09-28 03:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_settlementitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('SELLER_DEBIT', 'Seller Debit'), ('SELLER_CREDIT', 'Seller Credit'), ('REFUND', 'Refund'), ('DELIVERY_ADJUSTMENT', 'Delivery Adjustment'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_adjustments', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.settlement')),
            ],
            options={
                'db_table': 'finance_settlement_adjustments',
                'indexes': [models.Index(fields=['settlement'], name='fin_settle_adj_settle_idx'), models.Index(fields=['adjustment_type'], name='fin_settle_adj_type_idx'), models.Index(fields=['created_by'], name='fin_settle_adj_creator_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fin_settle_adj_amount_positive')],
            },
        ),
    ]
