# Generated by Django 5.2.17 on 2026-09-23 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='vehicles.vehiclemake')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['make', 'is_active'], name='vehicles_ve_make_id_fc9e0d_idx')],
                'constraints': [models.UniqueConstraint(fields=('make', 'name'), name='unique_vehicle_model_per_make'), models.UniqueConstraint(fields=('make', 'slug'), name='unique_vehicle_model_slug_per_make')],
            },
        ),
    ]
