# Generated by Django 5.2.17 on 2026-09-23 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='vehicles.vehiclemodel')),
            ],
            options={
                'ordering': ['year_from', 'name'],
                'indexes': [models.Index(fields=['model', 'is_active'], name='vehicles_ve_model_i_5431bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('model', 'name'), name='unique_vehicle_generation_per_model'), models.UniqueConstraint(fields=('model', 'slug'), name='unique_vehicle_generation_slug_per_model')],
            },
        ),
    ]
