# Generated by Django 5.2.17 on 2026-09-23 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiclegeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('power_hp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='vehicles.vehiclegeneration')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['generation', 'is_active'], name='vehicles_ve_generat_8beae1_idx')],
                'constraints': [models.UniqueConstraint(fields=('generation', 'name'), name='unique_vehicle_engine_per_generation'), models.UniqueConstraint(fields=('generation', 'code'), name='unique_vehicle_engine_code_per_generation')],
            },
        ),
    ]
