# Generated by Django 5.2.17 on 2026-09-23 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicleengine'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('market', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='vehicles.vehicleengine')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='vehicles.vehiclegeneration')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['generation', 'is_active'], name='vehicles_ve_generat_589e58_idx'), models.Index(fields=['engine', 'is_active'], name='vehicles_ve_engine__5f0704_idx')],
                'constraints': [models.UniqueConstraint(fields=('generation', 'engine', 'name'), name='unique_vehicle_variant'), models.UniqueConstraint(fields=('generation', 'engine', 'slug'), name='unique_vehicle_variant_slug')],
            },
        ),
    ]
