# Generated by Django 5.2.17 on 2026-09-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehiclevariant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclevariant',
            name='unique_vehicle_variant',
        ),
        migrations.RemoveConstraint(
            model_name='vehiclevariant',
            name='unique_vehicle_variant_slug',
        ),
        migrations.RemoveIndex(
            model_name='vehiclevariant',
            name='vehicles_ve_generat_589e58_idx',
        ),
        migrations.RemoveField(
            model_name='vehiclevariant',
            name='generation',
        ),
        migrations.AddConstraint(
            model_name='vehiclevariant',
            constraint=models.UniqueConstraint(fields=('engine', 'name'), name='unique_vehicle_variant'),
        ),
        migrations.AddConstraint(
            model_name='vehiclevariant',
            constraint=models.UniqueConstraint(fields=('engine', 'slug'), name='unique_vehicle_variant_slug'),
        ),
    ]
