# Generated by Django 5.2.17 on 2026-09-23 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_vehiclevariant_unique_vehicle_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('plate_number', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_vehicles', to='vehicles.vehiclevariant')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_default'], name='vehicles_cu_custome_03d5fe_idx'), models.Index(fields=['vehicle_variant'], name='vehicles_cu_vehicle_c3499d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer',), name='unique_default_vehicle_per_customer')],
            },
        ),
    ]
