# Generated by Django 5.2.17 on 2026-09-23 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_customervehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customervehicle',
            constraint=models.UniqueConstraint(fields=('customer', 'vehicle_variant'), name='unique_customer_vehicle_variant'),
        ),
    ]
