# Generated by Django 5.2.17 on 2026-09-24 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productcompatibility'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_sku', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to='stores.store')),
            ],
            options={
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['store', 'is_active'], name='stores_sell_store_i_24ac9a_idx'), models.Index(fields=['product', 'is_active'], name='stores_sell_product_7d6606_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='unique_store_product')],
            },
        ),
    ]
