# Generated by Django 5.2.17 on 2026-09-24 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('OEM', 'OEM'), ('AFTERMARKET', 'Aftermarket'), ('USED', 'Used')], default='AFTERMARKET', max_length=20)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('warranty', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'), models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_ca0f3c_idx'), models.Index(fields=['product_type', 'is_active'], name='catalog_pro_product_dffc87_idx')],
            },
        ),
    ]
