# Generated by Django 5.2.17 on 2026-09-24 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPartNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100)),
                ('normalized_part_number', models.CharField(db_index=True, editable=False, max_length=100)),
                ('number_type', models.CharField(choices=[('OEM', 'OEM'), ('MANUFACTURER', 'Manufacturer'), ('CROSS_REFERENCE', 'Cross Reference'), ('AFTERMARKET', 'Aftermarket')], default='MANUFACTURER', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_numbers', to='catalog.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_numbers', to='catalog.product')),
            ],
            options={
                'ordering': ['part_number'],
                'indexes': [models.Index(fields=['normalized_part_number', 'is_active'], name='catalog_pro_normali_3d4d00_idx'), models.Index(fields=['product', 'is_active'], name='catalog_pro_product_a8ed95_idx'), models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_30967f_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'normalized_part_number', 'number_type', 'brand'), name='unique_product_part_number')],
            },
        ),
    ]
