# Generated by Django 5.2.17 on 2026-09-24 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productpartnumber'),
        ('vehicles', '0008_customervehicle_unique_customer_vehicle_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatibilities', to='catalog.product')),
                ('vehicle_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_compatibilities', to='vehicles.vehiclevariant')),
            ],
            options={
                'ordering': ['product', 'vehicle_variant'],
                'indexes': [models.Index(fields=['product', 'status'], name='catalog_pro_product_5a9e42_idx'), models.Index(fields=['vehicle_variant', 'status'], name='catalog_pro_vehicle_12e1e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'vehicle_variant'), name='unique_product_vehicle_compatibility')],
            },
        ),
    ]
