# Generated by Django 5.2.17 on 2026-09-30 15:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_productcompatibility'),
        ('orders', '0005_deliveryassignment'),
        ('stores', '0003_store_unique_store_per_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HIDDEN', 'Hidden')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='stores.store')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='reviews_store_status_idx'), models.Index(fields=['product', 'status'], name='reviews_product_status_idx'), models.Index(fields=['customer', 'created_at'], name='reviews_customer_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'customer', 'store'), name='unique_store_review_per_order'), models.UniqueConstraint(fields=('order', 'customer', 'product'), name='unique_product_review_per_order')],
            },
        ),
    ]
