# Generated by Django 5.2.17 on 2026-10-01 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_REJECTED', 'Order Rejected'), ('ORDER_PREPARING', 'Order Preparing'), ('ORDER_READY', 'Order Ready'), ('ORDER_OUT_FOR_DELIVERY', 'Order Out For Delivery'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('REVIEW_CREATED', 'Review Created'), ('SETTLEMENT_READY', 'Settlement Ready')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=1000)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', 'created_at'], name='notif_recipient_created_idx'), models.Index(fields=['type', 'created_at'], name='notif_type_created_idx')],
            },
        ),
    ]
